#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := nad_nmb.o
ccflags-$(CONFIG_NAD_DRAM_HALF_GIG)  := -DNAD_DRAM_HALF_GIG
